# Based from https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
apiVersion: v1
kind: Service
metadata:
  name: sample-sts
  labels:
    app: sample-sts
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: sample-sts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-sts
spec:
  serviceName: sample-sts
  replicas: 2
  selector:
    matchLabels:
      app: sample-sts
  template:
    metadata:
      labels:
        app: sample-sts
    spec:
      containers:
      - name: sample-sts
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi