apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mssql
  name: mssql
spec:
  ports:
  - name: 1433-1433
    port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    used_for: workshop 
  clusterIP: None
status:
  loadBalancer: {}
