apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: exercise
  name: exercise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: exercise
    spec:
      containers:
      - image: test:v1
        name: test
        env:
        - name: APP_PORT
          value: "8080"
        - name: SERVER
          value: "mssql.test-gladys.svc.cluster.local"
        - name: USERNAME
          value: "sa"
        - name: PASSWORD
          value: "MyPassword1!"
        - name: DATABASE
          value: "master"
        resources: {}
status: {}
