apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-api
  name: my-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-api
    spec:
      initContainers:
      - name: init-1
        image: busybox
        command: ['sh', '-c', 'echo init script here']
        
      containers:
      - image: my-api:v1
        env:
        - name: APP_PORT
          value: "8080"
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              name: my-api-conf
              key: KEY_VARIABLE
        name: my-api
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
status: {}
